repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      name: isort (Python import sorter)
      language_version: python3.9
      args: ["--profile", "black", "--filter-files", "--apply"]

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      name: black (Python code formatter)
      language_version: python3.9

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      name: flake8 (Python linter)
      language_version: python3.9
      args: [--max-line-length=125]
