name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Build Docker image
        run: docker build -t my-flask-blog .
      - name: Push to ECR
        run: |
          # Steps to authenticate and push to AWS ECR (Elastic Container Registry)
          aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-ecr-url
          docker tag my-flask-blog:latest your-ecr-url/my-flask-blog:latest
          docker push your-ecr-url/my-flask-blog:latest
